[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "crispy-bootstrap5>=2025.4",
    "django>=5.2",
    "django-crispy-forms>=2.4",
    "pillow>=11.2.1",
    "psycopg2-binary>=2.9.10",
]
